### ISSUE TITLE
Try to lower the requirements

### ISSUE THREAD

**Issue by Onepierre** [Giglium/vinted_scraper#14]
Hello,
I'm trying to install your package and it seems unavailable 

```
pip install vinted_scraper

ERROR: Could not find a version that satisfies the requirement vinted_scraper (from versions: none)
ERROR: No matching distribution found for vinted_scraper
```
I get the same error with 
```
pip install vinted_scraper
```

Do you have any idea why?

**Comment by Onepierre** [comment]
My bad I had the wrong version of python. It doesn't work above Python 3.9

**Comment by Giglium** [comment]
Hi,
I'll reuse this issue to try to lower the module's requirements. The only reason for the actual requirements is that they met my local environment. But we can try to be as flexible as we can so everybody can use it.
