### ISSUE TITLE
Cannot fetch session cookie from 

### ISSUE THREAD

**Issue by roby222** [Giglium/vinted_scraper#51]
Sometimes I encountered this random failure using vinted.it domain for my search:

"  File "/vinted_env/lib/python3.12/site-packages/vinted_scraper/vintedWrapper.py", line 66, in _fetch_cookie
    raise RuntimeError(f"Cannot fetch session cookie from {self.baseurl}")
"

Is it possible to add a retry mechanism?

thank you

**Comment by Giglium** [comment]
Great idea! I've encountered the same problems and it's especially annoying in the pipeline. I've added a 3 times retry with a progressive timeout. You will found it on the version `2.3.0`
