### ISSUE TITLE
is it not working anymore?

### ISSUE THREAD

**Issue by Smoki-Cool** [Giglium/vinted_scraper#57]
I am unable to even initiate the VintedScraper class because of the following error:

RuntimeError: Cannot fetch session cookie from https://www.vinted.co.uk, because of status code: 403 different from 200.

Is it not working anymore? I tried another library and it didn't work either with the same status code 403

**Comment by Fedee0** [comment]
I opened a pr that fixes the issue, you may want to use my fork for the moment

**Comment by TurpeTing** [comment]
I have the same issue @Giglium

**Comment by Fedee0** [comment]
> > I opened a pr that fixes the issue, you may want to use my fork for the moment
> 
> Does it work with your cookie update pr? If you don't mind, may I ask if you were successful in using it with this small fix? Thanks!

It works for me with this fix, doesn't it work for you?

**Comment by Giglium** [comment]
@Fedee0 I tried to run the test of your PR but they failed, we should also fix the mock, so I can merge it!

So Vinted still uses the `_vinted_fr_session` but the API now wants the `access_token_web`? Interesting...

**Comment by Fedee0** [comment]
> @Fedee0 I tried to run the test of your PR but they failed, we should also fix the mock, so I can merge it!
> 
> So Vinted still uses the `_vinted_fr_session` but the API now wants the `access_token_web`? Interesting... 
> 

my fix indeed worked for me, and yes vinted still uses _vinted_fr_session although when sending requests it wants access_token_web

**Comment by Giglium** [comment]
fixed the test and released the new package: https://github.com/Giglium/vinted_scraper/releases/tag/2.3.1

Thanks, @Fedee0 for your contribution!
